# Generated by Django 4.2.23 on 2025-09-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParqueaderoPrivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dueno', models.CharField(max_length=100)),
                ('documento_tipo', models.CharField(max_length=20)),
                ('documento_numero', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=200)),
                ('nombre_comercial', models.CharField(blank=True, max_length=100, null=True)),
                ('espacios', models.PositiveIntegerField()),
                ('tipos_vehiculos', models.CharField(max_length=100)),
                ('ubicacion_mapa', models.CharField(blank=True, max_length=200, null=True)),
                ('politicas', models.TextField(blank=True, null=True)),
                ('foto_dueno', models.ImageField(upload_to='duenos_fotos/')),
            ],
        ),
    ]
