# Generated by Django 4.2.23 on 2025-09-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parqueaderoprivado'),
    ]

    operations = [
        migrations.AddField(
            model_name='parqueaderoprivado',
            name='foto_parqueadero',
            field=models.ImageField(default=None, upload_to='parqueaderos_fotos/'),
            preserve_default=False,
        ),
    ]
