# Generated by Django 4.2.23 on 2025-09-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_parqueaderoprivado_foto_parqueadero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parqueaderoprivado',
            name='ubicacion_mapa',
        ),
        migrations.AddField(
            model_name='parqueaderoprivado',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='parqueaderoprivado',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
