# Generated by Django 4.2.23 on 2025-09-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='parqueaderoprivado',
            name='tarifa_dia',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parqueaderoprivado',
            name='tarifa_hora',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
